apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-xmlstilling-ws
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-xmlstilling-ws
  port: 9022
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 40
    path: /isAlive
  readiness:
    initialDelay: 40
    path: /isAlive
  prometheus:
    enabled: true
    path: /prometheus
  webproxy: true
  vault:
    enabled: true
  ingresses:
  - https://pam-xmlstilling-ws.nais.oera-q.local
