server:
  port: 9022
ldap.domain: ${LDAP_DOMAIN}
ldap.url: ${LDAP_URL}
ROLE_EKSTERNBRUKER.groups: 0000-GA-XMLStilling-HR-bruker
db.name: xmlstilling-ws-preprod
spring:
  datasource:
    url: ${XMLSTILLING_DB_URL}
#    username: ${XMLSTILLING_DB_USERNAME}
#    password: ${XMLSTILLING_DB_PASSWORD}
    continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
       temp:
         use_jdbc_metadata_defaults: false
       generate_statistics: true
       cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  profiles:
    active: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
