server:
  port: 9022
ldap.url: ${LDAP_URL}
ldap.domain: ${LDAP_DOMAIN}
ROLE_EKSTERNBRUKER.groups: 0000-GA-XMLStilling-HR-bruker
database:
  name: xmlstilling-ws
  url: ${XMLSTILLING_DB_URL}
spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
       session:
         events:
           log: false
       temp:
         use_jdbc_metadata_defaults: false
       generate_statistics: true
       cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class:  org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  profiles:
    active: prod
  flyway:
    enabled: true
    baseline-on-migrate: true
vault:
  mount-path: postgresql/prod-fss
