server:
  port: 9022
#ldap.url: ${LDAP_URL}
#ldap.domain:
ROLE_EKSTERNBRUKER.groups: 0000-GA-XMLStilling-HR-bruker
ldap.serviceuser.basedn: ou=ServiceAccounts,dc=oera-q,dc=local
ldap.domain: OERA-Q.LOCAL
ldap.user.basedn: ou=NAV,ou=BusinessUnits,dc=oera-q,dc=local
ldap.basedn: dc=oera-q,dc=local
ldap.url: ldaps://ldapgw.oera-q.local
spring:
  datasource:
    url: ${XMLSTILLING_DB_URL:jdbc:oracle:thin:@d32dbfl003.oera-t.local:1521/sblarb_t1}
    username: ${XMLSTILLING_DB_USERNAME:six_komp}
    password: ${XMLSTILLING_DB_PASSWORD:<CHANGE_ME>}
